/* MySQL 生产适配示例：字段与 sql.txt 一致。开发演示默认走 models.js 的 JSON 适配层。 */
import { Sequelize, DataTypes } from 'sequelize';
const sequelize = new Sequelize(process.env.DB_NAME || 'haobangshou', process.env.DB_USER || 'root', process.env.DB_PASSWORD || '', { dialect: 'mysql', host: process.env.DB_HOST || '127.0.0.1', port: Number(process.env.DB_PORT || 3306), logging: false, define: { underscored: true, timestamps: true } });
export const User = sequelize.define('User', { id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, username: { type: DataTypes.STRING(30), unique: true }, passwordHash: DataTypes.STRING(100), role: DataTypes.ENUM('admin','user'), name: DataTypes.STRING(30), phone: DataTypes.STRING(11), bio: DataTypes.STRING(500) }, { tableName: 'users' });
export const Region = sequelize.define('Region', { id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, name: DataTypes.STRING(50), city: DataTypes.STRING(50), province: DataTypes.STRING(50) }, { tableName: 'regions' });
export const HelpRequest = sequelize.define('HelpRequest', { id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, userId: DataTypes.INTEGER, regionId: DataTypes.INTEGER, type: DataTypes.STRING(30), title: DataTypes.STRING(100), description: DataTypes.TEXT, attachment: DataTypes.STRING(255), status: DataTypes.TINYINT }, { tableName: 'help_requests' });
export const Response = sequelize.define('Response', { id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, requestId: DataTypes.INTEGER, userId: DataTypes.INTEGER, description: DataTypes.TEXT, attachment: DataTypes.STRING(255), status: DataTypes.TINYINT }, { tableName: 'responses' });
export const Success = sequelize.define('Success', { id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, requestId: DataTypes.INTEGER, responseId: DataTypes.INTEGER, acceptedAt: DataTypes.DATE }, { tableName: 'successes' });
User.hasMany(HelpRequest, { foreignKey: 'userId' }); HelpRequest.belongsTo(User, { foreignKey: 'userId', as: 'publisher' }); Region.hasMany(HelpRequest, { foreignKey: 'regionId' }); HelpRequest.belongsTo(Region, { foreignKey: 'regionId' }); HelpRequest.hasMany(Response, { foreignKey: 'requestId' }); Response.belongsTo(HelpRequest, { foreignKey: 'requestId' }); User.hasMany(Response, { foreignKey: 'userId' }); Response.belongsTo(User, { foreignKey: 'userId', as: 'responder' }); Response.hasOne(Success, { foreignKey: 'responseId' }); Success.belongsTo(Response, { foreignKey: 'responseId' });
export { sequelize };
